sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UA9AfjWqz2yg4qT+tI99IJqVIwtF8oN2e7QxIbuaIz4IGI45cgEzq1KmQiqqAmXdPx4qC5LqkfqrVr4iU19tHqNSyY6SfrBONXYqEdCBuPiys9jYKG3UZacoXpn24cjgH6orAxAnRpR9dxJG0VIgaafYlpOWtCfQESALDmbl48YWcEPoprmpGaWnd6mQIoyM57H/9mYp/P8JEAW7km97AS6tNIdjMIH6n+ZRjXGogRtjAOSXwxlBnn5/OjvJJyQ2uBOj31ucRK0DOvykfQ29wjoPQj67q5A/HhukdaBxCYS43lSWF1xdu/MB74OthChJgxRSfO5g7IKNO3sjf2UWxL4Tqbl1cWlw3rMaIp7PJZYOAF8XHYGBvagcPaOcl+AhfqMV+Ue9EGI7Z1BnoP3DZVtKJIkFqIW9qaowlWwhuf8RlibP+eF61/7PoKk7TUqhq0xl2PKlz7mcsxEkn3wQQ+cXOL0Gmxo4kMldBwRwFBTfSjXUecCzJuWWdbIPehsbrm+YQal3E0ZhO/dWlDwr5ZckTeO3hyNMM3QiPqE35+gEgIuAj0TLI1JGGi4NxKl3a/SIeTBJgBmOJabNGIyi6l9ZBSqa4twigMv++Av6Rh6JTliU5o1QZkYLwwAMNTfWVFnZW1tq+3kkaL6lwveyYTeKy3+7oYr8wU2jafjPGZ8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tales-and-Novels-of-J-de-La-Fontaine-Volume-06_5280
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy